### PR TITLE
ENH: Converted into installable package

### PR DESCRIPTION
**Pull request by wolfgang-noichl**
`pip install` is cleaner than pythonpath magic, and allows for easy updates, dependency handling,...

### CODE REVIEW

**Comment by jdoepfert** [comment]
Hi @wolfgang-noichl, thx for your contribution. I recently changed the code a bit and included automated tests, which would require some changes to your PR. Specifially, I'd like to have a separate folders for the package (as you did already), tests, and examples. Let me know if your still interested in working on that.

**Comment by wolfgang-noichl** [comment]
Sorry, I don't have any time for that right now. And I wouldn't enjoy re-doing that PR just because you didn't merge it when it was still easy ;P

**Comment by jdoepfert** [comment]
👍 thx for the update

**Comment by jdoepfert** [comment]
resolved by #12

**Pull request closed without merging**
